apiVersion: v1
kind: ConfigMap
metadata:
  name: env-config
data:
  AWS_BUCKET: nikolas-user-image-uploads
  AWS_PROFILE: project-4
  AWS_REGION: use-east-1
  JWT_SECRET: testing
  POSTGRESS_DB: postgres
  POSTGRESS_HOST: database-project-3.cf2ayvjbtx6y.us-east-1.rds.amazonaws.com
  URL: http://localhost:8100  
metadata:
  name: env-config